### ISSUE TITLE
floatingLabel animation not working. 

### ISSUE THREAD

**Issue by shivwork** [Sharlaan/material-ui-superselectfield#67]
floatingLabel should be up on field focus and down on focus out. Its working fine with multiple selections, but not in case of single selection.

**Comment by MaximilianPichler** [comment]
Hey! I've fixed it in version 1.0.2 over on my fork https://github.com/MaximilianPichler/material-ui-selectfield

**Comment by shivwork** [comment]
Installed "material-ui-selectfield": "^1.0.2".Still Not working.
On Focus : -
![open](https://user-images.githubusercontent.com/27669700/31397640-2acdbbba-ae04-11e7-9204-e9e85e642265.jpg)
Without Focus : -
![sdfdsfsdff](https://user-images.githubusercontent.com/27669700/31397641-2b0ffb56-ae04-11e7-90c7-d099e04ee333.jpg)

**Comment by MaximilianPichler** [comment]
Yeah sorry I noticed that bug after releasing. Check out the demo "Floating label" here https://maximilianpichler.github.io/material-ui-selectfield/
This is version 1.0.21
If you find any more issues please open an issue over on my fork.

**Comment by shivwork** [comment]
floatingLabel not working properly in singleSelection.
By default floatingLabel stays Up, it should be down. When i click the field its works great.

**Comment by Sharlaan** [comment]
v1.6.1 is out, should fix this issue.
Please confirm.

**Comment by shivwork** [comment]
Still not working.
<MaterialSelectField
      disabled={disabled ? disabled : false}
      showAutocompleteThreshold={1}
      errorText={touched && error}
      floatingLabel={label}
      hintText=''
      value={selectedObj}
      nb2show={7}
      anchorOrigin={{ vertical: 'top', horizontal: 'left' }}
      required={true}
      onChange={(e) => changeSelectedObj(e)}
      hoverColor='rgba(3, 169, 244, 0.15)'
    >
      {optionsList}
    </MaterialSelectField>

**Comment by Sharlaan** [comment]
At 1st glance, looks like you didnot read the documentation -again- :
- required prop isnot implemented yet
- anchorOrigin value is useless since it is the same as default value
- {disabled ? disabled : false} --> {disabled || false} is simpler
- when you "think" there is no option selected, **did you check the value of `selectedObj` is null** ? an empty object is still a valid **non null** value, so the floatingLabel will float above, while the component will show an empty field.

If the problem still persists, can you make a PR reproducing this issue ?

**Comment by Sharlaan** [comment]
Please check with latest version.
